# Generated by Django 3.0.7 on 2020-07-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0003_auto_20200712_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getquote',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.Customer'),
        ),
    ]
