# Generated by Django 3.0.7 on 2020-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0004_auto_20200712_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
