# Generated by Django 3.0.7 on 2020-08-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quote', '0005_getquote_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistoryModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=200)),
                ('suggested_price', models.FloatField()),
                ('total_due', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(choices=[('TX', 'Texas'), ('OTHERS', 'Out of Texas')], max_length=20)),
                ('zipcode', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='gallons_requested',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Getquote',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
