# Generated by Django 3.0.7 on 2020-08-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0005_getquote_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getquote',
            name='Address_1',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='Address_2',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='gallons_requested',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='state',
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='suggested_price',
        ),
        migrations.AlterField(
            model_name='getquote',
            name='name',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
