# Generated by Django 3.0.4 on 2020-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelpredictionsystem', '0004_auto_20200416_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('TX', 'Texas'), ('OTHERS', 'Out of Texas')], max_length=20),
        ),
    ]
