# Generated by Django 3.0.4 on 2020-04-19 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuelpredictionsystem', '0005_auto_20200418_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistoryModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_requested', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=200)),
                ('suggested_price', models.FloatField()),
                ('total_due', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
