# Generated by Django 3.0.4 on 2020-04-19 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuelpredictionsystem', '0006_pricehistorymodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistorymodule',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
