# Generated by Django 3.0.7 on 2020-08-02 17:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuelpredictionsystem', '0008_auto_20200419_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceHistoryModule',
            new_name='PricingHistory',
        ),
    ]
