# Generated by Django 3.0.7 on 2020-08-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelpredictionsystem', '0009_auto_20200802_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricinghistory',
            old_name='total_due',
            new_name='total_amount_due',
        ),
    ]
