<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-07-04 01:05
=======
# Generated by Django 3.0.7 on 2020-07-04 01:54
>>>>>>> 3d93e5142f48af0fc36707fc7d7cfb3e313bd70d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('sugestedPrice', models.FloatField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('deliveryDate', models.DateField()),
                ('gallonsRequested', models.FloatField()),
                ('Total', models.FloatField()),
=======
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('gallons_requested', models.FloatField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('suggested_price', models.FloatField(null=True)),
>>>>>>> 3d93e5142f48af0fc36707fc7d7cfb3e313bd70d
            ],
        ),
    ]
