# Generated by Django 3.0.7 on 2020-07-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='price',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
