# Generated by Django 3.0.7 on 2020-07-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200703_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='delivery_address1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='delivery_address2',
        ),
        migrations.AddField(
            model_name='quote',
            name='Address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='Address_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
