# Generated by Django 3.0.7 on 2020-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20200703_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='City',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='State',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Zip_Code',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
