# Generated by Django 3.0.7 on 2020-07-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20200705_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='total_price',
        ),
    ]
