# Generated by Django 3.0.7 on 2020-07-05 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0009_remove_pricing_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestedPrice', models.FloatField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('deliveryDate', models.DateField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('gallonsRequested', models.FloatField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
