# Generated by Django 3.0.7 on 2020-07-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_quoterequesthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='total_amount',
        ),
    ]
