# Generated by Django 3.0.7 on 2020-07-05 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0013_auto_20200705_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='QuoteRequestHistory',
        ),
    ]
