# Generated by Django 3.0.7 on 2020-07-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_auto_20200705_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.Customer'),
        ),
    ]
