# Generated by Django 3.0.7 on 2020-07-12 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0017_auto_20200711_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
        migrations.AddField(
            model_name='pricing',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='gallons_requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.Quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.Customer'),
        ),
    ]
