# Generated by Django 3.0.7 on 2020-07-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0018_auto_20200712_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='name',
        ),
    ]
